library(psych, warn.conflicts=F)
library(data.table, warn.conflicts=F)
library(ggplot2,warn.conflicts=F)
library(plotly,warn.conflicts=F)
library(expss,warn.conflicts=F)
library(tidyverse,warn.conflicts=F)
library(pander,warn.conflicts=F)
library(forcats,warn.conflicts=F)
library(stringr,warn.conflicts=F)
library(caTools,warn.conflicts=F)
library(VIM,warn.conflicts=F)
library(caret,warn.conflicts=F)
require(reshape2,warn.conflicts=F)
library(GGally,warn.conflicts=F)
library(corrplot,warn.conflicts=F)
library(factoextra,warn.conflicts=F)
library(gridExtra,warn.conflicts=F)
library(C50,warn.conflicts=F)
library(highcharter,warn.conflicts=F)
library(rpart,warn.conflicts=F)
library(e1071,warn.conflicts=F)
library(ranger,warn.conflicts=F)
library(epiR,warn.conflicts=F)
library(randomForest,warn.conflicts=F)
library(party,warn.conflicts=F)
library(class,warn.conflicts=F)
library(kknn,warn.conflicts=F) 
library(gbm,warn.conflicts=F)
library(ada,warn.conflicts=F)

data <- read.csv("../input/breast-cancer-wisconsin-data/data.csv", header=T)
str(data)
data<-data[,-33]